//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type_Product
    {
        public int Id { get; set; }
        public int Material_type_id { get; set; }
        public int Product_id { get; set; }
    
        public virtual Material_type Material_type { get; set; }
        public virtual Product Product { get; set; }
    }
}
