//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type
    {
        public Material_type()
        {
            this.Material_type_Product = new HashSet<Material_type_Product>();
        }
    
        public int Id { get; set; }
        public string Material_type1 { get; set; }
        public double Prosent_braka { get; set; }
    
        public virtual ICollection<Material_type_Product> Material_type_Product { get; set; }
    }
}
