//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPolDBEntities : DbContext
    {
        public MasterPolDBEntities()
            : base("name=MasterPolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_type> Material_type { get; set; }
        public DbSet<Material_type_Product> Material_type_Product { get; set; }
        public DbSet<Partner> Partner { get; set; }
        public DbSet<Partner_products> Partner_products { get; set; }
        public DbSet<Partner_type> Partner_type { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Product_type> Product_type { get; set; }
    }
}
