//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.Partner_products = new HashSet<Partner_products>();
        }
    
        public int Id { get; set; }
        public int Partner_type_id { get; set; }
        public string Partner_name { get; set; }
        public string Familia_director { get; set; }
        public string Name_director { get; set; }
        public string Othestvo_director { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Adress { get; set; }
        public string Inn { get; set; }
        public int Reiting { get; set; }
    
        public virtual Partner_type Partner_type { get; set; }
        public virtual ICollection<Partner_products> Partner_products { get; set; }
    }
}
