//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_type
    {
        public Partner_type()
        {
            this.Partner = new HashSet<Partner>();
        }
    
        public int Id { get; set; }
        public string Partner_type1 { get; set; }
    
        public virtual ICollection<Partner> Partner { get; set; }
    }
}
