//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_type
    {
        public Product_type()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Product_type1 { get; set; }
        public double Coff { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
